MedicalAssistanceFrom/Models/ErrorViewModel.cs
namespace MedicalAssistanceFrom.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MedicalAssistanceFrom/Controllers/HomeController.cs
using MedicalAssistanceFrom.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MedicalAssistanceFrom.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MedicalAssistanceFrom/Controllers/MedicalFormController.cs
using Domain_Layer.Data;
using Domain_Layer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Security.Cryptography.Xml;
using System;

namespace MedicalAssistanceFrom.Controllers
{
    public class MedicalFormController : Controller
    {
        private readonly MedicalFormDbContext medicalFormDbContext;
        private readonly MedicalFromModel medicalForm;

        public MedicalFormController(MedicalFormDbContext medicalFormDbContext, MedicalFromModel medicalForm)
        {
            this.medicalFormDbContext = medicalFormDbContext;
            this.medicalForm = medicalForm;
        }


        public IActionResult Add()

        {
            var viewModel = new medicalFromViewModel();
            return View(viewModel);
        }


        [HttpPost]
        public async Task<IActionResult> Add(medicalFromViewModel model, List<IFormFile> files, Files attachment)
        {

            foreach (var file in files)
            {
                var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                var fileModel = new Files
                {
                    createdDate = DateTime.Now,
                    Signature = model.Signature
                                        
                };

                using (var dataStream = new MemoryStream())
                {
                    await dataStream.CopyToAsync(dataStream);
                    fileModel.MedicalAttachments = dataStream.ToArray();
                    model.MedicalAttachmentFileName = fileName;
                }

                using (var dataStream = new MemoryStream())
                {
                    await dataStream.CopyToAsync(dataStream);
                    fileModel.ReverteeCertificate= dataStream.ToArray();
                    model.ReverteeCertificateFileName = fileName;
                }

                using (var memoryStream = new MemoryStream())
                {
                    await memoryStream.CopyToAsync(memoryStream);
                    fileModel.TravellingAttachment = memoryStream.ToArray();
                    model.ReverteeCertificateFileName = fileName;
                }

                using (var memoryStream = new MemoryStream())
                {
                    await memoryStream.CopyToAsync(memoryStream);
                    fileModel.OverSeaHospitalDocument = memoryStream.ToArray();
                    model.HospitalAttachmentFileName = fileName;
                }
               
                await medicalFormDbContext.MedicalFrom.AddAsync(fileModel);
            }

            attachment.Signature = Convert.ToBase64String(ConvertDataUrlToByteArray(attachment.Signature));

            var newForm = new MedicalFromModel()
                {
                    FirstName = model.FirstName,
                    SecondName = model.SecondName,
                    LastName = model.LastName,
                    IDNo = model.IDNo,
                    Email = model.Email,
                    TelPhone = model.TelPhone,
                    PoBoxNo = model.PoBoxNo,
                    Town = model.Town,
                    PatientRepName = model.PatientRepName,
                    PatientRepPhone = model.PatientRepPhone,
                    Relation = model.Relation,
                    NatureOfillness = model.NatureOfillness,
                    HospitalName = model.HospitalName,
                    County = model.County,
                    MedicalAttachmentDetails = model.MedicalAttachmentDetails,
                    MedicalAttachmentFileName = model.MedicalAttachmentFileName,
                    FamilyContribution = model.FamilyContribution,
                    NHIFcontribution = model.NHIFcontribution,
                    HospitalBillBalance = model.HospitalBillBalance,
                    IsRevertee = model.IsRevertee,
                    ReverteeCertificateFileName = model.ReverteeCertificateFileName,
                    AdditionalInfo = model.AdditionalInfo,
                    TransportDocument = model.AdditionalInfo,
                    TravellingAttachmentFileName = model.TravellingAttachmentFileName,
                    OverSeasHospitalName = model.OverSeasHospitalName,
                    OverSeaCountry = model.OverSeaCountry,
                    HospitalAttachmentFileName = model.HospitalAttachmentFileName,
                    Date = DateTime.Now,
                    createdDate = DateTime.Now,
                    modfiedDate = DateTime.Now,
                };
     
                await medicalFormDbContext.MedicalFrom.AddAsync(newForm);
                await medicalFormDbContext.SaveChangesAsync();


            

            return View(model);

        }

        //private void SaveAttachment (IFormFile file, ref byte[] target)
        //{   
        //        using (var memoryStream = new MemoryStream())
        //        {
        //            file.CopyTo(memoryStream);
        //             target = memoryStream.ToArray();
        //        }
            
        //}


        private byte[] ConvertDataUrlToByteArray(string dataUrl)
        {
            if (string.IsNullOrEmpty(dataUrl))
            {
                throw new ArgumentException(nameof(dataUrl), "dataUrl cannot be null or empty");

            }

            var dataParts = dataUrl.Split(',');

            if (dataParts.Length < 2 )
            {
                throw new ArgumentException("Invalid dataUrl format.", nameof(dataUrl));
            }
             var base64Data = dataUrl.Split(',')[1];

            return Convert.FromBase64String(base64Data);
        }

       

    }
};

MedicalAssistanceFrom/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MedicalAssistanceFrom/Views/MedicalForm/Add.cshtml
@model Domain_Layer.Models.medicalFromViewModel
@{
    ViewData["Title"] = "Signature Input";
}


<h1>Medical Assistance form</h1>
<br />

<form method="post" action="Add" >
    <h3>Enter Your Details</h3>
    <div class="row g-3">

        <div class="col-md-4">
            <label for="" class="form-label">First Name</label>
            <input type="text" class="form-control" asp-for="FirstName">
        </div>
        <div class="col-md-4">
            <label for="" class="form-label">Second Name</label>
            <input type="text" class="form-control" asp-for="SecondName">
        </div>
        <div class="col-md-4">
            <label for="" class="form-label">Last Name</label>
            <input type="text" class="form-control" asp-for="LastName">
        </div>
    </div>
    <br/>
    <div class="row g-3">
        <div class="col-md-4">
            <label for="" class="form-label">Enter Id/Passport No</label>
            <input type="number" class="form-control" asp-for="IDNo">
        </div>

        <div class="col-md-4">
            <label for="" class="form-label">Enter Phone No</label>
            <input type="text" class="form-control" asp-for="TelPhone">
        </div>

        <div class="col-md-4">
            <label for="" class="form-label">Enter Email</label>
            <input type="email" class="form-control" asp-for="Email">
        </div>
        <div class="col-md-6">
            <label for="" class="form-label">PoBox No.</label>
            <input type="number" class="form-control" asp-for="PoBoxNo">
        </div>
        <div class="col-md-6">
            <label for="" class="form-label">Town Of Residency</label>
            <input type="text" class="form-control" asp-for="Town">
        </div>
    </div>
    
    <br />
    <h3>Enter Patient Representative Details</h3>
    <br />
    <div class="row g-3">
        <div class="col-md-4">
            <label for="" class="form-label"> Name</label>
            <input type="text" class="form-control" asp-for="PatientRepName">
        </div>
        <div class="col-md-4">
            <label for="" class="form-label"> Phone No.</label>
            <input type="number" class="form-control" asp-for="PatientRepPhone">
        </div>
        <div class="col-md-4">
            <label for="" class="form-label"> Relationship</label>
            <input type="text" class="form-control" asp-for="Relation">
        </div>
    </div>
    <br />
    <h3>Other information</h3>
    <br />
    <div class="row g-3">
        <div class="col-md-4">
            <label for="" class="form-label"> Nature of Illness</label>
            <input type="text" class="form-control" asp-for="NatureOfillness">
        </div>
        <div class="col-md-4">
            <label for="" class="form-label"> Hospital Name</label>
            <input type="text" class="form-control" asp-for="HospitalName">
        </div>
        <div class="col-md-4">
            <label for="" class="form-label"> County of Residence</label>
            <input type="text" class="form-control" asp-for="County">
        </div>
    </div>
    <br />
    <h3>Medical Attachments</h3>
    <br />

    <div >
        
        <label for="IsBill" class="form-label"> Bills </label>
        <input type="radio" name="MedicalAttachment" asp-for="MedicalAttachmentDetails" value="Bill" id="IsBill">
    </div>
    <div class="mb-3">
        <label for="IsmedicalCorrespondence" class="form-label">Medical Correspondence </label>
        <input type="radio" name="MedicalAttachment" asp-for="MedicalAttachmentDetails" value="Medical Correspondence" Id="IsMedicalCorrespondence">
    </div>
    
    <div class="mb-3">
        <label for="IsDoctorsLetter" class="form-label"> Doctors Letter</label>
        <input type="radio" name="MedicalAttachment" asp-for="MedicalAttachmentDetails" value="Doctors Letter" id="IsDoctorsLetter">
    </div>
    <div class="mb-3">
        <label for="" class="form-label"> Others</label>
        <input type="radio" name="MedicalAttachment" asp-for="MedicalAttachmentDetails" value="Others" id="IsOthers">
    </div>

    <div class="mb-3">
        <label for="DocumentFile"> Medical Attachment:</label>
        <br/>
        <br />
        <input type="file"  name="MedicalAttachments" asp-for="dataFiles">
    </div>
    <br />
    @*<div class="mb-3">
        <label for="" class="form-label"> Patient Name</label>
        <input type="text" class="form-control" asp-for="HospitalAttachmentFileName">
    </div>*@
    <br />
    <h3>Payment information</h3> 
    <br />
    <div class="mb-3">
        <label for="" class="form-label"> Family Contribution</label>
        <input type="number" class="form-control" asp-for="FamilyContribution">
    </div>
    <div class="mb-3">
        <label for="" class="form-label"> Amount paid by NHIF</label>
        <input type="number" class="form-control" asp-for="NHIFcontribution">
    </div>
    <div class="mb-3">
        <label for="" class="form-label"> Hospital Balance</label>
        <input type="number" class="form-control" asp-for="HospitalBillBalance">
    </div>
    <br />
    <h3>If Revertee, attach certification information</h3>
    <br />

    <div class="mb-3">
        <label for="" class="form-label"> Yes</label>
        <input type="radio"  asp-for="IsRevertee" value="True" id="Revertee">
    </div>
    <div class="mb-3">
        <label for="" class="form-label"> No</label>
        <input type="radio"  asp-for="IsRevertee" value="False" id="Not revertee">
    </div>
    <div class="mb-3">
        <label for="DocumentFile" > Attach Revertee info</label>
        <br />
        <br />
        <input type="file" name="ReverteeCertificate" asp-for="dataFiles">
    </div>
    <br />
    @*<div class="mb-3">
        <label for="" class="form-label"> Revertee Name</label>
        <input type="text" class="form-control" asp-for="ReverteeCertificateFileName">
    </div>*@
    <br />

    <div class="mb-3">
        <label for="" class="form-label"> Additional information </label>
        <textarea type="text" class="form-control" asp-for="AdditionalInfo"></textarea>
    </div>
    <br />
    
    <h3>Traveling Details Overseas Attachment </h3>
    <br />
    <div class="mb-3">
        <label for="" class="form-label"> Passport</label>
        <input type="radio" asp-for="TransportDocument" value="Passport" for="1">
    </div>
    <div class="mb-3">
        <label for="" class="form-label"> Ticket</label>
        <input type="radio" asp-for="TransportDocument" value="Ticket" for="2">

    </div>
    <div class="mb-3">
        <label for="" class="form-label"> VISA</label>
        <input type="radio" asp-for="TransportDocument" value="VISA" for="3">
    </div>
    <div>
    <label for="DocumentFile"> Travel Documents attachment: </label>
        <br/>
        <br/>
        <input type="file" name="TravellingAttachment" asp-for="dataFiles">
    </div>
    <br />
    @*<div class="mb-3">
        <label for="" class="form-label"> User Name</label>
        <input type="text" class="form-control" asp-for="TravellingAttachmentFileName">
    </div>*@
    <br />
    <br />
    <h3>For Overseas Hospital Treatment</h3>
    <br />
    <div class="row g-3">
        <div class="col-md-4">
            <label for="" class="form-label"> Hospital Name</label>
            <input type="text" class="form-control" asp-for="OverSeasHospitalName">
        </div>
        <div class="col-md-4">
            <label for="" class="form-label"> County of Residence</label>
            <input type="text" class="form-control" asp-for="OverSeaCountry">
        </div>
        <br/>
        <br />
        <div class="mb-3">
            <label for="DocumentFile"> Hospital Documenatation: </label>
            <br />
            <br/>
            <input type="file" asp-for="dataFiles">
        </div>
        <br />
        @*<div class="mb-3">
            <label for="" class="form-label"> Hospital Name</label>
            <input type="text" class="form-control" asp-for="HospitalAttachmentFileName">
        </div>*@
    </div>
    <br />
    <br />
    <h3>Verification</h3>
    <br />
    <div class="row g-3">
        <div class="col-md-6">
            <label for="" class="form-label">Date</label>
            <input type="date" class="form-control" asp-for="Date">
        </div>
        @* <div class="col-md-3">
        <label for="" class="form-label"> ID</label>
        <input type="number" class="form-control" asp-for="Signature">
        </div>*@
        <div class="mb-6">
            <label for="" class="form-label">Signature</label>
            <br />
            <br/>

            <canvas id="signatureCanvas" width="400" height="200" style="border: 1px solid #000;"></canvas>
            <button id="clearButton">Clear Signature</button>
            
            <input type="hidden" id="signatureData" name="signatureData" asp-for="Signature"/>    
            
        </div>

    </div>
    <br/>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>

  
</form>

@section Scripts {
    <script>
        var signaturePad = new SignaturePad(document.getElementById('signatureCanvas'));

        document.getElementById('clearButton').addEventListener('click', function () {
            signaturePad.clear();
        });

        document.querySelector('form').addEventListener('submit', function (event){
            var dataUrl = signaturePad.toDataURL();
            document.getElementById('signatureData').ariaValueMax = dataUrl;
        });
    </script>
    
    }

MedicalAssistanceFrom/Views/Shared/EditorTemplates/SignaturePad.cshtml
@{
}



@model byte[]

<div class="signature-pad">
    <canvas width=" 200" height="100" style="border: 1px solid #000;"></canvas>
    <button type="button" class="btn btn-default btn-sm btn-clear-canvas"> Clear </button>
    
    @Html.HiddenFor(model => model, ViewData["htmlAttributes"])
</div>

MedicalAssistanceFrom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MedicalAssistanceFrom</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MedicalAssistanceFrom.styles.css" asp-append-version="true" />
    <script src="~/lib/signature_pad/signature_pad.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MedicalAssistanceFrom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MedicalForm" asp-action="Add">Medical Form</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MedicalAssistanceFrom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>